#!/usr/bin/env python3
"""Generate a standalone VTS analytics HTML dashboard from a JSON report.

This avoids Streamlit/pandas dependencies for environments where only the
Python standard library is available.
"""

from __future__ import annotations

import argparse
import html
import json
import os
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import make_interp_spline


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a static VTS dashboard HTML file.")
    parser.add_argument(
        "json_path",
        nargs="?",
        default="testmeet_analytics.json",
        help="Path to analytics JSON generated by hybrid_vts.py.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output HTML path. Defaults to <json_name>_dashboard.html.",
    )
    return parser.parse_args()


def default_output_path(json_path: str) -> str:
    base, _ = os.path.splitext(json_path)
    return f"{base}_dashboard.html"


def load_json(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError("Analytics JSON must contain an object at the top level.")
    return payload


def create_sentiment_timeline_plot(data: dict[str, Any], output_path: str) -> dict[str, Any]:
    """Render the sentiment timeline as a smoothed Matplotlib PNG."""

    rows = (data.get("sentiment") or {}).get("segments") or []
    x_raw = np.array([float(row.get("start_time") or 0) / 60 for row in rows], dtype=float)
    y_raw = np.array([float(row.get("polarity") or 0) for row in rows], dtype=float)

    order = np.argsort(x_raw)
    x_raw = x_raw[order]
    y_raw = y_raw[order]

    unique_x, unique_indices = np.unique(x_raw, return_index=True)
    unique_y = y_raw[unique_indices]

    fig, ax = plt.subplots(figsize=(12, 4.8), facecolor="#111827")
    ax.set_facecolor("#111827")

    interpolated_points = 0
    if len(unique_x) >= 4:
        x_smooth = np.linspace(float(unique_x.min()), float(unique_x.max()), 300)
        spline = make_interp_spline(unique_x, unique_y, k=3)
        y_smooth = np.clip(spline(x_smooth), -1, 1)
        ax.plot(x_smooth, y_smooth, color="#60a5fa", linewidth=3, label="Sentiment")
        interpolated_points = len(x_smooth)
    elif len(unique_x) >= 2:
        x_smooth = np.linspace(float(unique_x.min()), float(unique_x.max()), 300)
        y_smooth = np.interp(x_smooth, unique_x, unique_y)
        ax.plot(x_smooth, y_smooth, color="#60a5fa", linewidth=3, label="Sentiment")
        interpolated_points = len(x_smooth)
    elif len(unique_x) == 1:
        ax.scatter(unique_x, unique_y, color="#60a5fa", s=42, label="Sentiment")
        interpolated_points = 1

    if len(x_raw):
        point_colors = ["#34d399" if value > 0 else "#f87171" if value < 0 else "#fbbf24" for value in y_raw]
        ax.scatter(x_raw, y_raw, color=point_colors, edgecolor="#0f172a", linewidth=0.8, s=28, zorder=3)

    ax.set_xlabel("Time (minutes)", color="#f8fafc", fontsize=14)
    ax.set_ylabel("Sentiment", color="#f8fafc", fontsize=14)
    ax.set_ylim(-1, 1)
    ax.set_yticks([-1, 0, 1])
    ax.set_yticklabels(["Negative", "Neutral", "Positive"], color="#f8fafc", fontsize=12)
    ax.tick_params(axis="x", colors="#f8fafc", labelsize=12)
    ax.grid(True, color="#334155", linewidth=0.8, alpha=0.85)
    ax.legend(facecolor="#111827", edgecolor="#334155", labelcolor="#f8fafc")

    for spine in ax.spines.values():
        spine.set_color("#334155")

    fig.tight_layout()
    fig.savefig(output_path, dpi=160, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)

    return {
        "raw_points": int(len(x_raw)),
        "interpolated_points": int(interpolated_points),
        "x_label": "Time (minutes)",
        "y_tick_labels": ["Negative", "Neutral", "Positive"],
    }


def write_dashboard(data: dict[str, Any], output_path: str) -> None:
    encoded = json.dumps(data, ensure_ascii=False)
    title = html.escape("VTS Meeting Analytics Dashboard")
    output_base, _ = os.path.splitext(output_path)
    sentiment_image_path = f"{output_base}_sentiment_timeline.png"
    create_sentiment_timeline_plot(data, sentiment_image_path)
    sentiment_image_src = html.escape(os.path.basename(sentiment_image_path), quote=True)
    document = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    :root {{
      --bg: #0f172a;
      --panel: #111827;
      --panel-strong: #1f2937;
      --ink: #f8fafc;
      --muted: #cbd5e1;
      --line: #334155;
      --blue: #60a5fa;
      --green: #34d399;
      --red: #f87171;
      --amber: #fbbf24;
      --violet: #a78bfa;
      --teal: #2dd4bf;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      font-size: 18px;
      line-height: 1.55;
    }}
    header {{
      background: #020617;
      border-bottom: 1px solid var(--line);
      padding: 28px 32px 20px;
      position: sticky;
      top: 0;
      z-index: 3;
    }}
    h1 {{
      margin: 0 0 6px;
      font-size: 36px;
      font-weight: 800;
      letter-spacing: 0;
    }}
    .subtitle {{
      color: var(--muted);
      font-size: 18px;
    }}
    main {{
      max-width: 1320px;
      margin: 0 auto;
      padding: 22px;
    }}
    .metrics {{
      display: grid;
      grid-template-columns: repeat(6, minmax(0, 1fr));
      gap: 12px;
      margin-bottom: 18px;
    }}
    .metric, .panel {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      box-shadow: 0 18px 44px rgba(0, 0, 0, 0.24);
    }}
    .metric {{
      padding: 18px 18px;
      min-height: 112px;
    }}
    .label {{
      color: var(--muted);
      font-size: 15px;
      text-transform: uppercase;
      font-weight: 700;
    }}
    .value {{
      margin-top: 10px;
      font-size: 34px;
      font-weight: 800;
    }}
    .grid {{
      display: grid;
      grid-template-columns: minmax(0, 1.35fr) minmax(340px, 0.65fr);
      gap: 14px;
      margin-bottom: 14px;
    }}
    .panel {{
      padding: 20px;
      min-width: 0;
    }}
    .panel h2 {{
      margin: 0 0 16px;
      font-size: 24px;
      font-weight: 800;
    }}
    canvas {{
      display: block;
      width: 100%;
      height: 360px;
    }}
    .chart-image {{
      display: block;
      width: 100%;
      min-height: 360px;
      object-fit: contain;
    }}
    .short canvas {{ height: 280px; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 17px;
    }}
    th, td {{
      padding: 10px 8px;
      border-bottom: 1px solid var(--line);
      text-align: left;
      vertical-align: top;
    }}
    th {{
      color: var(--muted);
      font-size: 15px;
      text-transform: uppercase;
    }}
    .pill-row {{
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }}
    .pill {{
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 9px 12px;
      background: var(--panel-strong);
      font-size: 16px;
    }}
    .timeline {{
      display: grid;
      gap: 8px;
    }}
    .event {{
      display: grid;
      grid-template-columns: 68px 120px 44px 1fr;
      gap: 10px;
      padding: 9px 0;
      border-bottom: 1px solid var(--line);
      font-size: 16px;
    }}
    .lang {{
      font-weight: 750;
      color: var(--teal);
      text-transform: uppercase;
    }}
    .muted {{ color: var(--muted); }}
    .quality {{
      display: grid;
      grid-template-columns: 220px 1fr;
      gap: 12px;
      align-items: center;
    }}
    .breakdown {{
      display: grid;
      gap: 10px;
    }}
    .bar-track {{
      background: #334155;
      height: 12px;
      border-radius: 999px;
      overflow: hidden;
      margin-top: 5px;
    }}
    .bar-fill {{
      height: 100%;
      background: var(--blue);
      border-radius: 999px;
    }}
    @media (max-width: 980px) {{
      .metrics {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
      .grid {{ grid-template-columns: 1fr; }}
      .quality {{ grid-template-columns: 1fr; }}
      header {{ position: static; }}
    }}
    @media (max-width: 620px) {{
      main {{ padding: 12px; }}
      .metrics {{ grid-template-columns: 1fr; }}
      .event {{ grid-template-columns: 56px 1fr 40px; }}
      .event .text {{ grid-column: 1 / -1; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>VTS Meeting Analytics Dashboard</h1>
    <div class="subtitle" id="subtitle"></div>
  </header>
  <main>
    <section class="metrics" id="metrics"></section>

    <section class="grid">
      <div class="panel">
        <h2>Speaking Time</h2>
        <canvas id="speakerChart"></canvas>
      </div>
      <div class="panel short">
        <h2>Meeting Quality</h2>
        <div class="quality">
          <canvas id="qualityGauge"></canvas>
          <div class="breakdown" id="qualityBreakdown"></div>
        </div>
      </div>
    </section>

    <section class="grid">
      <div class="panel">
        <h2>Sentiment Timeline</h2>
        <img id="sentimentChart" class="chart-image" src="{sentiment_image_src}" alt="Sentiment timeline">
      </div>
      <div class="panel short">
        <h2>Language Distribution</h2>
        <canvas id="languageChart"></canvas>
      </div>
    </section>

    <section class="grid">
      <div class="panel">
        <h2>Speaker Metrics</h2>
        <div id="speakerTable"></div>
      </div>
      <div class="panel">
        <h2>Turn Taking</h2>
        <div id="turnTable"></div>
      </div>
    </section>

    <section class="grid">
      <div class="panel">
        <h2>Language Timeline</h2>
        <div class="timeline" id="languageTimeline"></div>
      </div>
      <div class="panel">
        <h2>Keywords</h2>
        <div class="pill-row" id="keywords"></div>
      </div>
    </section>
  </main>
  <script id="analytics-data" type="application/json">{encoded}</script>
  <script>
    const data = JSON.parse(document.getElementById('analytics-data').textContent);
    const colors = ['#60a5fa', '#34d399', '#fbbf24', '#a78bfa', '#2dd4bf', '#f87171'];
    const fmt = new Intl.NumberFormat(undefined, {{ maximumFractionDigits: 1 }});

    function setCanvasSize(canvas) {{
      const rect = canvas.getBoundingClientRect();
      const ratio = window.devicePixelRatio || 1;
      canvas.width = Math.max(1, Math.floor(rect.width * ratio));
      canvas.height = Math.max(1, Math.floor(rect.height * ratio));
      const ctx = canvas.getContext('2d');
      ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
      return {{ ctx, w: rect.width, h: rect.height }};
    }}

    function metric(label, value) {{
      return `<div class="metric"><div class="label">${{label}}</div><div class="value">${{value}}</div></div>`;
    }}

    function renderMetrics() {{
      const summary = data.summary || {{}};
      const quality = data.quality || {{}};
      document.getElementById('subtitle').textContent =
        `${{summary.utterances || 0}} utterances across ${{summary.unique_speakers || 0}} speakers`;
      document.getElementById('metrics').innerHTML = [
        metric('Quality', `${{fmt.format(quality.score || 0)}}/100`),
        metric('Duration', `${{fmt.format(summary.total_meeting_duration || 0)}}s`),
        metric('Speakers', summary.unique_speakers || 0),
        metric('Languages', summary.languages_used || 0),
        metric('Utterances', summary.utterances || 0),
        metric('Balance', `${{fmt.format(data.participation_balance || 0)}}/100`)
      ].join('');
    }}

    function drawBarChart() {{
      const canvas = document.getElementById('speakerChart');
      const {{ ctx, w, h }} = setCanvasSize(canvas);
      const rows = ((data.speakers || {{}}).stats || []);
      const pad = {{ l: 56, r: 28, t: 24, b: 98 }};
      const max = Math.max(...rows.map(r => r.total_speaking_time || 0), 1);
      ctx.clearRect(0, 0, w, h);
      ctx.strokeStyle = '#334155';
      ctx.beginPath();
      ctx.moveTo(pad.l, pad.t);
      ctx.lineTo(pad.l, h - pad.b);
      ctx.lineTo(w - pad.r, h - pad.b);
      ctx.stroke();
      const slot = (w - pad.l - pad.r) / Math.max(rows.length, 1);
      const bw = Math.max(38, slot * 0.54);
      rows.forEach((r, i) => {{
        const x = pad.l + slot * i + (slot - bw) / 2;
        const bh = ((h - pad.t - pad.b) * (r.total_speaking_time || 0)) / max;
        const y = h - pad.b - bh;
        ctx.fillStyle = colors[i % colors.length];
        ctx.fillRect(x, y, bw, bh);
        ctx.fillStyle = '#f8fafc';
        ctx.font = '700 18px system-ui';
        ctx.textAlign = 'center';
        ctx.fillText(`${{fmt.format(r.total_speaking_time || 0)}}s`, x + bw / 2, y - 6);
        ctx.fillStyle = '#e2e8f0';
        ctx.font = '700 18px system-ui';
        const label = String(r.speaker || '');
        const words = label.split(' ');
        if (words.length > 1 && ctx.measureText(label).width > slot - 8) {{
          ctx.fillText(words.slice(0, -1).join(' '), x + bw / 2, h - pad.b + 26);
          ctx.fillText(words[words.length - 1], x + bw / 2, h - pad.b + 48);
        }} else {{
          ctx.fillText(label, x + bw / 2, h - pad.b + 34);
        }}
      }});
    }}

    function drawGauge() {{
      const canvas = document.getElementById('qualityGauge');
      const {{ ctx, w, h }} = setCanvasSize(canvas);
      const score = Math.max(0, Math.min(100, ((data.quality || {{}}).score || 0)));
      const cx = w / 2;
      const cy = h * 0.7;
      const radius = Math.min(w * 0.38, h * 0.55);
      ctx.clearRect(0, 0, w, h);
      ctx.lineWidth = 18;
      ctx.lineCap = 'round';
      ctx.strokeStyle = '#334155';
      ctx.beginPath();
      ctx.arc(cx, cy, radius, Math.PI, 0);
      ctx.stroke();
      ctx.strokeStyle = score >= 70 ? '#34d399' : score >= 50 ? '#fbbf24' : '#f87171';
      ctx.beginPath();
      ctx.arc(cx, cy, radius, Math.PI, Math.PI + Math.PI * score / 100);
      ctx.stroke();
      ctx.fillStyle = '#f8fafc';
      ctx.font = '700 32px system-ui';
      ctx.textAlign = 'center';
      ctx.fillText(fmt.format(score), cx, cy - 8);
      ctx.font = '13px system-ui';
      ctx.fillStyle = '#cbd5e1';
      ctx.fillText('out of 100', cx, cy + 18);
    }}

    function renderBreakdown() {{
      const breakdown = ((data.quality || {{}}).breakdown || {{}});
      document.getElementById('qualityBreakdown').innerHTML = Object.entries(breakdown).map(([k, v]) => `
        <div>
          <div class="label">${{k.replaceAll('_', ' ')}}: ${{fmt.format(v || 0)}}</div>
          <div class="bar-track"><div class="bar-fill" style="width:${{Math.max(0, Math.min(100, v || 0))}}%"></div></div>
        </div>
      `).join('');
    }}

    function drawDonut() {{
      const canvas = document.getElementById('languageChart');
      const {{ ctx, w, h }} = setCanvasSize(canvas);
      const rows = ((data.languages || {{}}).distribution || []);
      const total = rows.reduce((sum, r) => sum + (r.segments || 0), 0) || 1;
      const cx = w * 0.42;
      const cy = h / 2;
      const radius = Math.min(w, h) * 0.28;
      let start = -Math.PI / 2;
      ctx.clearRect(0, 0, w, h);
      rows.forEach((r, i) => {{
        const angle = (r.segments || 0) / total * Math.PI * 2;
        ctx.fillStyle = colors[i % colors.length];
        ctx.beginPath();
        ctx.moveTo(cx, cy);
        ctx.arc(cx, cy, radius, start, start + angle);
        ctx.closePath();
        ctx.fill();
        start += angle;
      }});
      ctx.fillStyle = '#111827';
      ctx.beginPath();
      ctx.arc(cx, cy, radius * 0.58, 0, Math.PI * 2);
      ctx.fill();
      rows.forEach((r, i) => {{
        const y = 34 + i * 25;
        ctx.fillStyle = colors[i % colors.length];
        ctx.fillRect(w * 0.72, y - 10, 12, 12);
        ctx.fillStyle = '#f8fafc';
        ctx.font = '16px system-ui';
        ctx.textAlign = 'left';
        ctx.fillText(`${{String(r.detected_language || '').toUpperCase()}} ${{fmt.format(r.segment_pct || 0)}}%`, w * 0.72 + 18, y);
      }});
    }}

    function table(headers, rows) {{
      return `<table><thead><tr>${{headers.map(h => `<th>${{h}}</th>`).join('')}}</tr></thead><tbody>${{rows.join('')}}</tbody></table>`;
    }}

    function renderTables() {{
      const speakers = ((data.speakers || {{}}).stats || []);
      document.getElementById('speakerTable').innerHTML = table(
        ['Speaker', 'Time', 'Share', 'Segments'],
        speakers.map(r => `<tr><td>${{r.speaker}}</td><td>${{fmt.format(r.total_speaking_time || 0)}}s</td><td>${{fmt.format(r.speaking_time_pct || 0)}}%</td><td>${{r.segment_count || 0}}</td></tr>`)
      );
      const turns = ((data.turn_taking || {{}}).transition_counts || []);
      document.getElementById('turnTable').innerHTML = turns.length ? table(
        ['From', 'To', 'Count'],
        turns.map(r => `<tr><td>${{r.from_speaker}}</td><td>${{r.to_speaker}}</td><td>${{r.count}}</td></tr>`)
      ) : '<div class="muted">No speaker transitions detected.</div>';
    }}

    function renderTimeline() {{
      const rows = ((data.sentiment || {{}}).segments || []).slice(0, 80);
      document.getElementById('languageTimeline').innerHTML = rows.map(r => `
        <div class="event">
          <div class="muted">${{fmt.format(r.start_time || 0)}}s</div>
          <div>${{r.speaker || ''}}</div>
          <div class="lang">${{r.detected_language || 'unk'}}</div>
          <div class="text">${{r.text || ''}}</div>
        </div>
      `).join('');
    }}

    function renderKeywords() {{
      const keywords = data.keywords || [];
      document.getElementById('keywords').innerHTML = keywords.map(k =>
        `<span class="pill">${{k.word}} <span class="muted">${{k.frequency}}</span></span>`
      ).join('');
    }}

    function render() {{
      renderMetrics();
      drawBarChart();
      drawGauge();
      renderBreakdown();
      drawDonut();
      renderTables();
      renderTimeline();
      renderKeywords();
    }}
    window.addEventListener('resize', render);
    render();
  </script>
</body>
</html>
"""
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write(document)


def main() -> int:
    args = parse_args()
    output_path = args.output or default_output_path(args.json_path)
    try:
        data = load_json(args.json_path)
        write_dashboard(data, output_path)
    except Exception as exc:
        print(f"Error: {exc}")
        return 1
    print(f"Dashboard saved to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
